import re
from typing import List, Optional, Any, Dict
from pydantic import BaseModel, Field

# Common regex patterns
SHELF_NAME_PATTERN = r"^shelves/[a-zA-Z0-9\-]+$"
BOOK_NAME_PATTERN = r"^shelves/[a-zA-Z0-9\-]+/books/[a-zA-Z0-9\-]+$"

class ProblemDetails(BaseModel):
    type: str = Field(description="A URI reference that identifies the problem type.", json_schema_extra={"format": "uri-reference"})
    title: str = Field(description="A short, human-readable summary of the problem type.")
    status: int = Field(description="The HTTP status code generated by the origin server for this occurrence of the problem.")
    detail: Optional[str] = Field(None, description="A human-readable explanation specific to this occurrence of the problem.", json_schema_extra={"type": "string"})
    instance: Optional[str] = Field(None, description="A URI reference that identifies the specific occurrence of the problem.", json_schema_extra={"format": "uri-reference", "type": "string"})

    model_config = {
        "json_schema_extra": {
            "title": "Problem Details"
        }
    }

class Shelf(BaseModel):
    path: Optional[str] = Field(default=None, pattern=SHELF_NAME_PATTERN, description="The resource path.", json_schema_extra={"readOnly": True, "type": "string"})
    theme: str = Field(description="The theme of the shelf.")

    model_config = {
        "json_schema_extra": {
            "x-aep-resource": {
                "type": "library.example.com/shelf",
                "singular": "shelf",
                "plural": "shelves",
                "patterns": ["shelves/{shelf}"]
            }
        }
    }

class Book(BaseModel):
    path: Optional[str] = Field(default=None, pattern=BOOK_NAME_PATTERN, description="The resource path.", json_schema_extra={"readOnly": True, "type": "string"})
    title: str = Field(description="The title of the book.")
    author: str = Field(description="The author of the book.")

    model_config = {
        "json_schema_extra": {
            "x-aep-resource": {
                "type": "library.example.com/book",
                "singular": "book",
                "plural": "books",
                "patterns": ["shelves/{shelf}/books/{book}"]
            }
        }
    }

class ListShelvesResponse(BaseModel):
    shelves: List[Shelf]
    next_page_token: str = ""

class ListBooksResponse(BaseModel):
    books: List[Book]
    next_page_token: str = ""

class ShelfUpdate(BaseModel):
    path: Optional[str] = Field(default=None, pattern=SHELF_NAME_PATTERN, description="The resource path.", json_schema_extra={"readOnly": True, "type": "string"})
    theme: Optional[str] = None

    model_config = {
        "json_schema_extra": {
            "x-aep-resource": {
                "type": "library.example.com/shelf",
                "singular": "shelf",
                "plural": "shelves",
                "patterns": ["shelves/{shelf}"]
            }
        }
    }

class BookUpdate(BaseModel):
    path: Optional[str] = Field(default=None, pattern=BOOK_NAME_PATTERN, description="The resource path.", json_schema_extra={"readOnly": True, "type": "string"})
    title: Optional[str] = None
    author: Optional[str] = None

    model_config = {
        "json_schema_extra": {
            "x-aep-resource": {
                "type": "library.example.com/book",
                "singular": "book",
                "plural": "books",
                "patterns": ["shelves/{shelf}/books/{book}"]
            }
        }
    }
